version: "2.0"
services:
  my-@project.artifactId@:
    container_name: my-@project.artifactId@
    image: prasannjeet/@project.artifactId@:@project.version@
    ports:
      - "8080:8080"
      - "8084:8443"
      - "5007:5005"
    env_file:
      - template.env

  mysql-@project.artifactId@:
    image: mysql/mysql-server:8.0.23
    container_name: mysql-@project.artifactId@
    ports:
      - "3306:3306"
    env_file:
      - template.env
    command: --lower_case_table_names=1
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local